version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    container_name: pg-docker
    restart: always
    environment:
      - POSTGRES_DB=jjmusic
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin!123
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./apps/api/src/db/init.sql:/docker-entrypoint-initdb.d/./apps/api/src/db/init.sql
volumes:
  database-data:
