version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    container_name: pg-docker
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jjmusic
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
